---
title: "Yamlet Cascading Aesthetics"
format: 
  html:
    self-contained: true
editor_options: 
  chunk_output_type: console
---

## Behavior

Plotting a decorated data.frame in ggplot() has special behavior for aesthetics
defined using yamlet decorations.  If there is only one dataset (typical), the 
aesthetics are coordinated with the (levels of the) corresponding variable.

If one or more additional layers provide non-default data, any decorations therein
override decorations previously specified for the same variable and aesthetic.
This is consistent with how ggplot() handles repeated definitions for labels:
the last provided label "wins". 

Furthermore, additional default decorations are propagated to secondary 
datasets where undefined.

## Example

In the example below, points are plotted using the observed data, then 
summary data is plotted as a separate layer, supplying its own data.
the plot is rendered _without_ decorations (left) and _with_ decorations (right).

 * Notice that the y axis label is 'concentration' (or similar) not 'mean', 
   consistent with default ggplot behavior where no label is supplied.
 * Notice that the label for color and shape is 'Subset', not 'Groups', 
   because the last layer wins; default ggplot behavior where label is supplied.
 * Likewise, colors are blue and magenta, not green and yellow, because the 
   summary layer was supplied last.
 * The summary layer respects the linetype defined earlier, having
   no such definition (decoration) in its own data.
 * The observations layer respects the shapes defined with the summary
   layer, which in fact are not even used by the summary layer.
   
This example is a bit contrived for heuristic value.  It makes more sense
to define aesthetics in the data supplied to the layer that uses them. 
As a best practice, consider specifying all aesthetics in the default data only.


```{r message = FALSE}
#| label: Layered Aesthetics
#| fig.width: 5.02
#| fig.height: 3.28
#| out.width: 200%

library(magrittr)
library(ggplot2)
library(yamlet)
library(dplyr)
library(metaplot)

set.seed(10)
obs <- data.frame(
  time = 1:100,
  group = c('a','b'),
  concentration = rnorm(100)
)

# observed data
obs %<>% decorate('
  time: [ Time, h ]
  concentration: [ Concentration, ng/mL ]
  group: [ 
    Group, 
    [ a, b ], 
    color: [ green, yellow ] , 
    linetype: [ dashed, dotdash ]
  ]
')

# summary data
sum <- obs %>% group_by(group) %>% summarize(mean = mean(concentration))
sum %<>% undecorate %>% decorate('
  group: [ 
    Subset, 
    [ a, b ], 
    color: [ blue, magenta ], 
    shape: [ 15, 19 ]
  ]
')


q <- obs %>%
  undecorate %>%
  ggplot(aes(time, concentration)) +
  geom_point(aes(color = group, shape = group)) +
  geom_hline(
    data = undecorate(sum), 
    aes(
      yintercept = mean, 
      color = group, 
      linetype = group
    )
  ) + 
  theme(legend.position = "top") +
  labs(subtitle = 'without decorations') +
  symmetric()

p <- obs %>%
  resolve %>%
  ggplot(aes(time, concentration)) +
  geom_point(aes(color = group, shape = group)) +
  geom_hline(
    data = resolve(sum), 
    aes(
      yintercept = mean, 
      color = group, 
      linetype = group
    )
  ) + 
  theme(legend.position = "top") +
  labs(subtitle = 'with decorations') + 
  symmetric()


multiplot(q, p) # %>% devsize(2,2)

sessionInfo()
```
